---
- name: Create pods using deployment
  hosts: kubernetes
  #become: true
  user: ubuntu


  tasks:
  - name: create a deployment
    command: kubectl apply -f angdeployment.yml
  - name:
    command: kubectl apply -f angservice.yml
  - name: rollout
    command: kubectl rollout restart deployment.v1.apps/tomcat-deployment
