---
- name: Create pods using deployment
  hosts: server
  #become: true
  user: kadmin

  tasks:
  - name: copying files 
   # become: true
    copy:
      src: /home/ansadmin/ans/
      dest: /home/kadmin/
  - name: Pod Creation
    command: "{{ item }}"
    with_items:
     - kubectl apply -f mysql-configmap.yml
     - kubectl apply -f mysqldb-root-credentials.yml
     - kubectl apply -f mysqldb-credentials.yml
     - kubectl apply -f mysql-deployment.yml
     - kubectl apply -f deployment.yml
     - kubectl rollout restart deployment.v1.apps/springboot-k8s-mysql
    environment:
      KUBECONFIG: /home/kadmin/.kube/config
    when: inventory_hostname == "192.168.0.144"
